name: auto-merge

on:
  pull_request_target:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        with:
          # NOTE!!! Cannot use secrets.GITHUB_TOKEN as it doesn't have enough scope permissions 
          # so a specific one has ot be created.
          # See https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/33
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
          command: 'squash and merge'
          target: minor
